-- lua/config/trouble.lua
-- Configuración de Trouble para diagnósticos

require('trouble').setup({
  mode = 'workspace_diagnostics',
  auto_preview = false,
  auto_fold = false,
  auto_jump = {},
  cycle_results = true,
  position = 'bottom',
  height = 10,
  width = 50,
  icons = true,
  multiline = true,
  indent_lines = true,
  win_config = {
    border = 'single',
  },
  include_declaration = false,
  cycle_results = true,
  action_keys = {
    close = 'q',
    cancel = '<esc>',
    refresh = 'r',
    jump = { '<cr>', '<tab>' },
    open_in_browser = 'gx',
    copy_to_clipboard = '<C-c>',
    toggle_preview = 'P',
    switch_severity = 's',
    toggle_preview = 'P',
    preview = 'p',
    close_folds = 'zM',
    open_folds = 'zR',
    toggle_fold = 'za',
    previous = 'k',
    next = 'j',
    help = '?',
  },
  multiline = true,
  indent_lines = true,
  win_config = {
    border = 'single',
  },
  auto_preview = false,
  auto_fold = false,
  auto_jump = {},
  include_declaration = false,
  signs = {
    error = ' ',
    warning = ' ',
    hint = ' ',
    information = ' ',
    other = ' ',
  },
  use_diagnostic_signs = false,
  action_keys = {
    close = 'q',
    cancel = '<esc>',
    refresh = 'r',
    jump = { '<cr>', '<tab>' },
    open_in_browser = 'gx',
    copy_to_clipboard = '<C-c>',
    toggle_preview = 'P',
    switch_severity = 's',
    toggle_preview = 'P',
    preview = 'p',
    close_folds = 'zM',
    open_folds = 'zR',
    toggle_fold = 'za',
    previous = 'k',
    next = 'j',
    help = '?',
  },
}) 